name: 'Validate Dev Container Configuration'
description:
  'Validates that required VS Code extensions are configured in
  devcontainer.json'
author: 'Chris Reddington'

inputs:
  required-extensions:
    description: 'Comma-separated list of required VS Code extensions'
    required: true
    default: 'GitHub.codespaces,github.vscode-github-actions,GitHub.copilot,GitHub.copilot-chat,github.copilot-workspace,GitHub.vscode-pull-request-github,GitHub.remotehub,GitHub.vscode-codeql'
  devcontainer-path:
    description: 'Path to devcontainer.json file'
    required: false
    default: '.devcontainer/devcontainer.json'
  validate-tasks:
    description: 'Enable validation of build, test, and run tasks'
    required: false
    default: 'false'
  required-features:
    description: 'Comma-separated list of required devcontainer features'
    required: false
    default: ''

runs:
  using: node20
  main: dist/index.js
